######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 12 20:10:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
