######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 21 22:39:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ticker.h
SOURCES += main.cpp ticker.cpp
