######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 5 20:00:46 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += atest.h testrunner.h
SOURCES += atest.cpp main.cpp
