######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 20 22:47:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              grids \
              hexspinbox \
              iconeditor \
              iconeditorplugin \
              grids/find \
              grids/gotocell \
              grids/sort \
              qtwui/hangman \
              qtwui/testapp \
              qtwui/include/QtWui \
              qtwui/src/http \
              qtwui/src/kernel \
              qtwui/src/webgets
INCLUDEPATH += . \
               grids \
               grids/find \
               grids/gotocell \
               grids/sort \
               hexspinbox \
               iconeditor \
               qtwui/hangman \
               qtwui/testapp

# Input
HEADERS += grids/cell.h \
           grids/mainwindow.h \
           grids/spreadsheet.h \
           hexspinbox/hexdialog.h \
           hexspinbox/hexspinbox.h \
           iconeditor/iconeditor.h \
           grids/find/finddialog.h \
           grids/gotocell/gotocelldialog.h \
           grids/sort/sortdialog.h \
           qtwui/hangman/Game.h \
           qtwui/hangman/HangMan.h \
           qtwui/testapp/TestWebget.h \
           qtwui/include/QtWui/qwuiabstracthttpserver.h \
           qtwui/include/QtWui/qwuiabstracthttpserverdelegate.h \
           qtwui/include/QtWui/qwuiabstractressource.h \
           qtwui/include/QtWui/qwuiabstractressourceprovider.h \
           qtwui/include/QtWui/qwuiabstractressourceproviderfactory.h \
           qtwui/include/QtWui/qwuiajaxinsertion.h \
           qtwui/include/QtWui/qwuiapplication.h \
           qtwui/include/QtWui/qwuiapplicationcreator.h \
           qtwui/include/QtWui/qwuiapplicationfactory.h \
           qtwui/include/QtWui/qwuiapplicationserver.h \
           qtwui/include/QtWui/qwuiborderstyle.h \
           qtwui/include/QtWui/qwuiboxlayout.h \
           qtwui/include/QtWui/qwuibufferedressource.h \
           qtwui/include/QtWui/qwuifcgidevice.h \
           qtwui/include/QtWui/qwuifileressource.h \
           qtwui/include/QtWui/qwuifileressourceprovider.h \
           qtwui/include/QtWui/qwuiglobal.h \
           qtwui/include/QtWui/qwuigridlayout.h \
           qtwui/include/QtWui/qwuihboxlayout.h \
           qtwui/include/QtWui/qwuihttpserver.h \
           qtwui/include/QtWui/qwuihttpserverdelegate.h \
           qtwui/include/QtWui/qwuilabel.h \
           qtwui/include/QtWui/qwuilayout.h \
           qtwui/include/QtWui/qwuilayoutitem.h \
           qtwui/include/QtWui/qwuimainwebget.h \
           qtwui/include/QtWui/qwuimessageressource.h \
           qtwui/include/QtWui/qwuiparameters.h \
           qtwui/include/QtWui/qwuiressourceproviderfactory.h \
           qtwui/include/QtWui/qwuiressourceproviderserver.h \
           qtwui/include/QtWui/qwuiscrollarea.h \
           qtwui/include/QtWui/qwuispaceritem.h \
           qtwui/include/QtWui/qwuistackedlayout.h \
           qtwui/include/QtWui/qwuistackedwebget.h \
           qtwui/include/QtWui/qwuitag.h \
           qtwui/include/QtWui/qwuitcpserver.h \
           qtwui/include/QtWui/qwuivboxlayout.h \
           qtwui/include/QtWui/qwuiwebget.h \
           qtwui/include/QtWui/qwuiwebgetitem.h \
           qtwui/src/http/qwuiabstracthttpserver.h \
           qtwui/src/http/qwuiabstracthttpserverdelegate.h \
           qtwui/src/http/qwuiabstractressource.h \
           qtwui/src/http/qwuiabstractressourceprovider.h \
           qtwui/src/http/qwuiabstractressourceproviderfactory.h \
           qtwui/src/http/qwuifcgidevice.h \
           qtwui/src/http/qwuihttpserver.h \
           qtwui/src/http/qwuihttpserverdelegate.h \
           qtwui/src/http/qwuimessageressource.h \
           qtwui/src/http/qwuiressourceproviderfactory.h \
           qtwui/src/http/qwuiressourceproviderserver.h \
           qtwui/src/http/qwuitcpserver.h \
           qtwui/src/kernel/qwuiapplication.h \
           qtwui/src/kernel/qwuiapplicationcreator.h \
           qtwui/src/kernel/qwuiapplicationfactory.h \
           qtwui/src/kernel/qwuiapplicationserver.h \
           qtwui/src/kernel/qwuiboxlayout.h \
           qtwui/src/kernel/qwuibufferedressource.h \
           qtwui/src/kernel/qwuifileressource.h \
           qtwui/src/kernel/qwuifileressourceprovider.h \
           qtwui/src/kernel/qwuiglobal.h \
           qtwui/src/kernel/qwuigridlayout.h \
           qtwui/src/kernel/qwuilayout.h \
           qtwui/src/kernel/qwuilayoutitem.h \
           qtwui/src/kernel/qwuiparameters.h \
           qtwui/src/kernel/qwuistackedlayout.h \
           qtwui/src/kernel/qwuitag.h \
           qtwui/src/webgets/qwuilabel.h \
           qtwui/src/webgets/qwuimainwebget.h \
           qtwui/src/webgets/qwuiscrollarea.h \
           qtwui/src/webgets/qwuistackedwebget.h \
           qtwui/src/webgets/qwuiwebget.h
FORMS += dialog.ui grids/gotocell/gotocelldialog.ui grids/sort/sortdialog.ui
SOURCES += splitter.cpp \
           grids/cell.cpp \
           grids/main.cpp \
           grids/mainwindow.cpp \
           grids/spreadsheet.cpp \
           hexspinbox/dialog.cpp \
           hexspinbox/hexspinbox.cpp \
           iconeditor/iconeditor.cpp \
           iconeditorplugin/iconeditorplugin.cpp \
           grids/find/finddialog.cpp \
           grids/gotocell/gotocelldialog.cpp \
           grids/sort/sortdialog.cpp \
           qtwui/hangman/Game.cpp \
           qtwui/hangman/HangMan.cpp \
           qtwui/hangman/main.cpp \
           qtwui/testapp/main.cpp \
           qtwui/testapp/TestWebget.cpp \
           qtwui/src/http/qwuiabstracthttpserver.cpp \
           qtwui/src/http/qwuiabstracthttpserverdelegate.cpp \
           qtwui/src/http/qwuiabstractressource.cpp \
           qtwui/src/http/qwuiabstractressourceprovider.cpp \
           qtwui/src/http/qwuiabstractressourceproviderfactory.cpp \
           qtwui/src/http/qwuifcgidevice.cpp \
           qtwui/src/http/qwuihttpserver.cpp \
           qtwui/src/http/qwuihttpserverdelegate.cpp \
           qtwui/src/http/qwuimessageressource.cpp \
           qtwui/src/http/qwuiressourceproviderserver.cpp \
           qtwui/src/http/qwuitcpserver.cpp \
           qtwui/src/kernel/qwuiapplication.cpp \
           qtwui/src/kernel/qwuiapplicationfactory.cpp \
           qtwui/src/kernel/qwuiapplicationserver.cpp \
           qtwui/src/kernel/qwuiboxlayout.cpp \
           qtwui/src/kernel/qwuibufferedressource.cpp \
           qtwui/src/kernel/qwuifileressource.cpp \
           qtwui/src/kernel/qwuifileressourceprovider.cpp \
           qtwui/src/kernel/qwuigridlayout.cpp \
           qtwui/src/kernel/qwuilayout.cpp \
           qtwui/src/kernel/qwuilayoutitem.cpp \
           qtwui/src/kernel/qwuiparameters.cpp \
           qtwui/src/kernel/qwuistackedlayout.cpp \
           qtwui/src/kernel/qwuitag.cpp \
           qtwui/src/webgets/qwuilabel.cpp \
           qtwui/src/webgets/qwuimainwebget.cpp \
           qtwui/src/webgets/qwuiscrollarea.cpp \
           qtwui/src/webgets/qwuistackedwebget.cpp \
           qtwui/src/webgets/qwuiwebget.cpp
RESOURCES += grids/spreadsheet.qrc iconeditorplugin/iconeditorplugin.qrc
