######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 20 22:16:32 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += iconeditorplugin.cpp
RESOURCES += iconeditorplugin.qrc
