######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 12 09:26:29 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui_testrunner.h guitesty.h
SOURCES += guitesty.cpp main.cpp
