######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 5 20:17:45 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testrunner.h testy.h
SOURCES += main.cpp testy.cpp
