######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 22:01:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += oventimer.h
SOURCES += main.cpp oventimer.cpp
