######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 12 08:21:44 2014
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += guitesty.h testrunner.h
SOURCES += guitesty.cpp main.cpp
