######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 20 22:48:03 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += splitter.cpp
